//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInfo
    {
        public AddressInfo()
        {
            this.StudentInfoes = new HashSet<StudentInfo>();
        }
    
        public decimal AddressID { get; set; }
        public Nullable<decimal> FK_TestInfoID { get; set; }
        public string AddressI { get; set; }
        public string AddressII { get; set; }
        public string ZipOrPostalCode { get; set; }
        public string Telephone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
    
        public virtual TestInfo TestInfo { get; set; }
        public virtual ICollection<StudentInfo> StudentInfoes { get; set; }
    }
}
