//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeUse
    {
        public OfficeUse()
        {
            this.TestInfoes = new HashSet<TestInfo>();
        }
    
        public decimal OfficeUseID { get; set; }
        public string Scheme { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> DateofPayment { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<bool> IDChecked { get; set; }
        public Nullable<bool> AC { get; set; }
        public Nullable<bool> GT { get; set; }
        public string AdministratorInitials { get; set; }
    
        public virtual ICollection<TestInfo> TestInfoes { get; set; }
    }
}
