//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public StudentInfo()
        {
            this.TestInfoes = new HashSet<TestInfo>();
        }
    
        public decimal StudentID { get; set; }
        public Nullable<decimal> FK_AddressID { get; set; }
        public string Title { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string IdentityType { get; set; }
        public string IdentityValue { get; set; }
        public string CountryNationalCode { get; set; }
        public string FirstLanguageCode { get; set; }
        public string OccupationSector { get; set; }
        public string OccupationLevel { get; set; }
        public string ApplyingCountry { get; set; }
        public string EnglishLearningLocation { get; set; }
        public string EducationLevel { get; set; }
        public string EnglishLearningPeriod { get; set; }
        public string PermanentDisability { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual ICollection<TestInfo> TestInfoes { get; set; }
    }
}
